server:
  port: 8080
spring:
  application:
    #应用名称 , 可选
    name: mt_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_mt?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: ztt202812
        #初始化连接数
      initial-size: 1
      #最小空闲连接
      min-idle: 1
      #最大活动连接
      max-active: 20
      #获取连接时测试是否可用
      test-on-borrow: true
      #监控页面启动
      filter:
        wall:
          config:
            start-transaction-allow: true
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射 address_book ---> AddressBook
    map-underscore-to-camel-case: true
    #日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
mt:
  sms:
    accessKeyId: LTAI5tGpJm6RjpyaBKQxSX6X # 你自己的accessKeyId
    accessKeySecret: VWwEIFGDcL84QOjBWvYdF8TIoLw7pU # 你自己的AccessKeySecret
    signName: 易购商城 # 签名名称
    verifyCodeTemplate: SMS_198922052 # 模板名称
email:
  userName: 2192316287@qq.com
  password: ejdzmqavbyosecfh



